In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"D:\Computer courses\Internship project\My_Projects\Spam Detection\combined_spam_data.csv")

In [3]:
df.head()

label                                               text
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get your medircations online qnb ikud v...
2      0   computer connection from cnn com wednesday es...
3      1  university degree obtain a prosperous future m...
4      0  thanks for all your answers guys i know i shou...

In [4]:
df.tail()

label                                               text
83443      0  hi given a date how do i get the last date of ...
83444      1  now you can order software on cd or download i...
83445      1  dear valued member canadianpharmacy provides a...
83446      0  subscribe change profile contact us long term ...
83447      1  get the most out of life ! viagra has helped m...

In [5]:
df.describe()

label
count  83448.000000
mean       0.526196
std        0.499316
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83448 entries, 0 to 83447
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   label   83448 non-null  int64 
 1   text    83448 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.3+ MB


In [13]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [14]:
ps = PorterStemmer()

In [15]:
corpus = []

for i in range(0, len(df.text)):
    review = re.sub('[^a-zA-z]', ' ', df['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [16]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [17]:
tf = TfidfVectorizer(stop_words= 'english')

In [18]:
x = corpus
y = df.label

In [19]:
from sklearn.model_selection import train_test_split as tts

In [20]:
xtrain, xtest, ytrain, ytest = tts(x, y, test_size = .2, random_state=10)

In [21]:
xtrain_tf = tf.fit_transform(xtrain)
xtest_tf = tf.transform(xtest)

In [22]:
nb = MultinomialNB()
nb1 = nb.fit(xtrain_tf, ytrain)

In [23]:
pred_tf = nb1.predict(xtest_tf)
pred_tf

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)

In [24]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [26]:
pd.crosstab(ytest, pred_tf)

col_0     0     1
label            
0      7799   135
1       285  8471

In [27]:
print(classification_report(ytest, pred_tf))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97      7934
           1       0.98      0.97      0.98      8756

    accuracy                           0.97     16690
   macro avg       0.97      0.98      0.97     16690
weighted avg       0.98      0.97      0.97     16690



### Spam filter

In [28]:
msg = input('Enter a message : ')
xmsg = tf.transform([msg])
ypred = nb.predict(xmsg)
ypred

Enter a message : click this link


array([1], dtype=int64)

In [29]:
msg = input('Enter a message : ')
xmsg = tf.transform([msg])
ypred = nb.predict(xmsg)
ypred

Enter a message : hi, this is anitha


array([0], dtype=int64)